### DISCUSSION TITLE
I am planning to add multiple variables support in one element

### DISCUSSION THREAD

**Discussion by stevenlei** [triggerjs/trigger#34] [Ideas]
Usually, we want to update several CSS properties in one go. For now, we have to wrap a few elements to archive this, for example, if we want to fade in an element and move it:

```html
<div tg-name="move" tg-from="-200" tg-to"200">
  <div tg-name="opacity" tg-from="0" tg-to="1">
    <span>Hello World</span>
  </div>
</div>
```

```css
span {
  transform: translate(var(--move) * 1px);
  opacity: var(--opacity);
}
```

To make it simple, I would like to change to:

```html
<div
    tg-name="opacity, move"
    tg-from:opacity="0"
    tg-to:opacity="1"
    tg-from:move="-200"
    tg-to:move="200"
  >
    <span>Hello World</span>
</div>
```

```css
span {
  transform: translate(var(--move) * 1px);
  opacity: var(--opacity);
}
```

Please feel free to comment, thank you.
